;this file for FamiTone2 library generated by text2data tool

bad_touch:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $ca,$c8,$c6,$c5,$c5,$c3,$c2,$c2,$c1,$02,$c0,$00,$0a
@env2:
	.byte $cb,$ca,$c9,$c8,$c7,$c5,$c4,$c3,$c3,$c2,$03,$c1,$03,$c1,$00,$0d
@env3:
	.byte $cf,$cd,$ca,$c7,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$03,$c0,$00,$0c
@env4:
	.byte $cf,$cd,$c7,$c3,$c1,$c0,$00,$05
@env5:
	.byte $cf,$cd,$c9,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c1,$00,$0a


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $f9,$85
@ref1:
	.byte $f9,$85
@ref2:
	.byte $82,$4b,$4b,$4a,$85,$4b,$4b,$4e,$85,$53,$53,$53,$55,$53,$53,$52
	.byte $85,$4f,$4f,$4f,$4f,$4f,$4f,$4f,$4f,$53,$53,$53,$53,$4a,$8d
@ref3:
	.byte $4b,$4b,$4a,$85,$4b,$4b,$4e,$85,$53,$53,$53,$55,$53,$53,$52,$85
	.byte $4f,$4f,$4f,$4f,$4f,$4f,$4f,$4f,$53,$53,$53,$53,$4a,$8d
	.byte $ff,$1e
	.word @ref3
	.byte $ff,$1e
	.word @ref3
@ref6:
	.byte $58,$85,$59,$59,$5d,$59,$5d,$59,$52,$85,$59,$59,$5d,$59,$5d,$59
	.byte $60,$85,$59,$59,$5d,$59,$5d,$59,$52,$83,$52,$83,$53,$54,$52,$54
	.byte $4a,$87
	.byte $ff,$22
	.word @ref6
@ref8:
	.byte $4a,$85,$4b,$4b,$53,$54,$85,$4b,$53,$53,$55,$52,$85,$4b,$4f,$53
	.byte $4e,$85,$61,$61,$59,$55,$49,$4b,$53,$53,$55,$52,$91
@ref9:
	.byte $4a,$85,$4b,$4b,$53,$54,$85,$4b,$53,$53,$55,$52,$85,$4b,$4f,$53
	.byte $4e,$85,$61,$61,$59,$55,$49,$4b,$53,$53,$55,$4a,$91
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref10:
	.byte $f9,$85
@ref11:
	.byte $f9,$85
@ref12:
	.byte $80,$2d,$45,$2d,$45,$2d,$45,$2d,$45,$33,$4b,$33,$4b,$33,$4b,$33
	.byte $4b,$29,$41,$29,$41,$29,$41,$29,$41,$25,$3d,$25,$3d,$25,$3d,$25
	.byte $3c,$81
@ref13:
	.byte $2d,$45,$2d,$45,$2d,$45,$2d,$45,$33,$4b,$33,$4b,$33,$4b,$33,$4b
	.byte $29,$41,$29,$41,$29,$41,$29,$41,$25,$3d,$25,$3d,$25,$3d,$25,$3c
	.byte $81
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
	.byte $ff,$21
	.word @ref12
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref30:
	.byte $f9,$81,$84,$02,$81
@ref31:
	.byte $03,$88,$1b,$86,$0d,$88,$1b,$84,$03,$88,$1b,$86,$0d,$88,$1b,$84
	.byte $03,$88,$1b,$86,$0d,$88,$1b,$84,$03,$88,$1b,$86,$0d,$88,$1b,$84
	.byte $03,$88,$1b,$86,$0d,$88,$1b,$84,$03,$88,$1b,$86,$0d,$88,$1b,$84
	.byte $03,$88,$1b,$86,$0d,$88,$1b,$84,$02,$02,$88,$1a,$84,$02,$86,$0d
	.byte $84,$02,$81
	.byte $ff,$23
	.word @ref31
	.byte $ff,$23
	.word @ref31
	.byte $ff,$23
	.word @ref31
	.byte $ff,$23
	.word @ref31
	.byte $ff,$23
	.word @ref31
	.byte $ff,$23
	.word @ref31
	.byte $ff,$23
	.word @ref31
	.byte $ff,$23
	.word @ref31
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref40:
	.byte $f9,$85
@ref41:
	.byte $f9,$85
@ref42:
	.byte $f9,$85
@ref43:
	.byte $f9,$85
@ref44:
	.byte $f9,$85
@ref45:
	.byte $f9,$85
@ref46:
	.byte $f9,$85
@ref47:
	.byte $f9,$85
@ref48:
	.byte $f9,$85
@ref49:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
